import { AppContent } from '@/components/common/app-content';
import 'antd/dist/reset.css';
import type { Metadata } from 'next';
import '../../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <AppContent>
        <main className='app'>{children}</main>
      </AppContent>
    </>
  );
}

export default MainLayout;
