import { AntdStyleProvider } from '@/lib/AntdStyleProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='app'>
          <AntdStyleProvider>{children}</AntdStyleProvider>
        </main>
      </body>
    </html>
  );
}

export default RootLayout;
