import { AppContent } from '@/components/common/app-content';
import { NavBar } from '@/components/common/navbar';
import Providers from '@/utils/providers';
import { Layout } from 'antd';
import 'antd/dist/reset.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Layout className='layout'>
            <NavBar />
            <AppContent>
              <main className='app'>{children}</main>
            </AppContent>
          </Layout>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
