/* tslint:disable */
/* eslint-disable */
/**
 * Reddit Clone API
 * Clone Reddit With Spring Boot.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommentDto } from './comment-dto';
/**
 * 
 * @export
 * @interface BaseApiResponseListCommentDto
 */
export interface BaseApiResponseListCommentDto {
    /**
     * 
     * @type {number}
     * @memberof BaseApiResponseListCommentDto
     */
    status?: number;
    /**
     * 
     * @type {Array<CommentDto>}
     * @memberof BaseApiResponseListCommentDto
     */
    data?: Array<CommentDto>;
}
