/* tslint:disable */
/* eslint-disable */
/**
 * Reddit Clone API
 * Clone Reddit With Spring Boot.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BaseResponseWithoutData
 */
export interface BaseResponseWithoutData {
    /**
     * 
     * @type {number}
     * @memberof BaseResponseWithoutData
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseWithoutData
     */
    message?: string;
}
