/* tslint:disable */
/* eslint-disable */
/**
 * Reddit Clone API
 * Clone Reddit With Spring Boot.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface BaseApiResponseUser
 */
export interface BaseApiResponseUser {
    /**
     * 
     * @type {number}
     * @memberof BaseApiResponseUser
     */
    status?: number;
    /**
     * 
     * @type {User}
     * @memberof BaseApiResponseUser
     */
    data?: User;
}
