/* tslint:disable */
/* eslint-disable */
/**
 * Reddit Clone API
 * Clone Reddit With Spring Boot.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CommentDto
 */
export interface CommentDto {
    /**
     * 
     * @type {number}
     * @memberof CommentDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentDto
     */
    postId?: number;
    /**
     * 
     * @type {Date}
     * @memberof CommentDto
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    userName?: string;
}
